### PR TITLE
Update PiHole version

### PR DESCRIPTION
**Pull request by dangior**

### CODE REVIEW

**Comment by krachlatte** [comment]
@dangior how can i contribute here to get this through?

what do need to do ?

how do i do the test that pihole 2022.11.02 works ? and push it in here or confim it here ?

**Review by krachlatte — COMMENTED** [review]
seams legit, container upgrade

**Comment by dangior** [comment]
@krachlatte is the official PiHole upgrade, for testing you can download the PR, build the image and install it locally

**Comment by krachlatte** [comment]
> 

clone your PR
but building does not work

/dangior/one-container/pihole-unbound# ./build_and_push.sh
unknown flag: --build-arg
See 'docker --help'.

**Comment by dangior** [comment]
@krachlatte according to Chris Crowe in [build file](https://github.com/chriscrowe/docker-pihole-unbound/blob/main/one-container/pihole-unbound/build_and_push.sh) you need to run this command first:
`docker buildx create --use --name build --node build --driver-opt network=host`

Also keep in mind to point to your own Docker Hub account.

If you don't want to do all these stuff you can just download this image from my Hub: [dangior/pihole-unbound:2022.11.2](https://hub.docker.com/repository/docker/dangior/pihole-unbound)

**Pull request closed without merging**
