### PR TITLE
Upgrading base container to 2023.01.10

### PR DESCRIPTION
**Pull request by peterlewis**

### CODE REVIEW

**Comment by kartone** [comment]
@peterlewis can you walk me through on how to get the images updated with your commit? Thanks

**Comment by peterlewis** [comment]
Sure. I updated [my images](https://hub.docker.com/repository/docker/peterlewis/pihole-unbound/general) following the process in the following:

https://github.com/chriscrowe/docker-pihole-unbound/blob/main/one-container/pihole-unbound/build_and_push.sh

Prior to undertaking the actions in the above script, I created the repository in Docker Hub, and then replaced `cbcrowe` with `peterlewis` to ensure it was pushing to my own account.

**Comment by kartone** [comment]
> Sure. I updated [my images](https://hub.docker.com/repository/docker/peterlewis/pihole-unbound/general) following the process in the following:
> 
> https://github.com/chriscrowe/docker-pihole-unbound/blob/main/one-container/pihole-unbound/build_and_push.sh
> 
> Prior to undertaking the actions in the above script, I created the repository in Docker Hub, and then replaced `cbcrowe` with `peterlewis` to ensure it was pushing to my own account.

Used your own images :) thanks

**Comment by kartone** [comment]
> No worries, just to let you know that once @chriscrowe updates his image, I plan to switch back to his repo and delete mine as he's active on this project, which is great! :)

Thanks for letting me know. I wish I would help somehow.

**Pull request closed without merging**
